apiVersion: v1
kind: Service
metadata:
  name: stockanalyzer
  namespace: {{ .Release.Namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: stockanalyzer
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
