# Development environment overrides
# Used with: helm upgrade --install stockanalyzer ./charts/stockanalyzer \
#             -f charts/stockanalyzer/values.yaml \
#             -f environments/dev/values.yaml

replicaCount: 1

image:
  tag: dev-f7b391c
  pullPolicy: Always

autoscaling:
  enabled: false
